import vm from 'node:vm';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const sandbox={window:{addEventListener(){}},document:{readyState:'loading',addEventListener(){}},TextDecoder,console};
vm.createContext(sandbox);
vm.runInContext(fs.readFileSync('web/assets/detriment-workspace.js','utf8'),sandbox);
const api=sandbox.window.ICMDetriment;
assert.equal(api.escape('<001>'),'&lt;001&gt;');
assert.equal(api.detectReport('Worst case\nNode ID\tFlood volume (m³)\n001\t8'),'auto');
assert.equal(api.detectReport('Time,Node ID,Flow (L/s)\n2025-01-01,001,3'),null);
assert.equal(api.detectReport('Seconds,Level\n0,1'),null);
assert.equal(api.csvCell('=SUM(A1)'), '"\'=SUM(A1)"');
assert.equal(api.csvCell(-.30000000000000004),'"-0.30000000000000004"');
assert.equal(api.csvCell('001'),'"001"');
const r={kind:'flooding',rows:[{asset_id:'001',status:'detriment',a:2,b:8,delta:6,flags:['flood_detriment'],unit:'m³'}],criteria:{threshold:5},scenario_a:{name:'Existing',sha256:'abc'},scenario_b:{name:'Proposed',sha256:'xyz'},method:'unrounded'};
assert.match(api.csv(r,r.rows),/threshold/);
assert.match(api.csv(r,r.rows),/"abc"/);
assert.equal(api.filterRows(r.rows,'detriment','001').length,1);
assert.equal(api.filterRows(r.rows,'unresolved','').length,0);
assert.equal(api.isReport({status:'ready',parsed:{metadata:{source_kind:'detriment_report'}}}),true);
assert.equal(api.isReport({status:'ready',parsed:{format:'csv'}}),false);
console.log('Detriment browser units passed.');
// Existing hydraulic QA must ignore report tables even in a mixed source pool.
const elements={gapInput:{value:'900'},healthBody:{innerHTML:''}};
const runtime={window:{},console,document:{getElementById:id=>elements[id]||null,querySelector:()=>null},setTimeout,clearTimeout,requestAnimationFrame:fn=>fn(),crypto:globalThis.crypto,localStorage:{getItem:()=>null},Worker:class{}};
vm.createContext(runtime);
vm.runInContext(fs.readFileSync('web/assets/runtime.release.js','utf8').replace(/start\(\);\s*$/,''),runtime);
vm.runInContext(`state.files.set('report',{id:'report',status:'ready',displayName:'flood.csv',virtualPath:'/report',parsed:{metadata:{source_kind:'detriment_report'},columns:['Flood volume']}});state.files.set('series',{id:'series',status:'ready',displayName:'series.csv',virtualPath:'/series',parsed:{columns:['Flow (L/s)']}});engine.call=async(name,args)=>({weekly:[{channel:args.path,rag:'Green'}]});`,runtime);
assert.equal(vm.runInContext('allSeries().length',runtime),1);
assert.equal(vm.runInContext("hydraulicSeriesForItem(state.files.get('report')).length",runtime),0);
await vm.runInContext('runHealth()',runtime);
assert.equal(vm.runInContext('state.healthResult.rows.length',runtime),1,'Health excludes non-timeseries reports');
console.log('Mixed-source hydraulic isolation passed.');
