import vm from 'node:vm';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const nodes=new Map();
for(const id of ['observedSelect','rainSelect'])nodes.set(id,{value:''});
nodes.set('modelSelect',{selectedOptions:[]});
nodes.set('seriesSemanticsPanel',{});
nodes.set('seriesSemanticsRows',{innerHTML:'',querySelectorAll:()=>[]});
const sandbox={window:{},document:{getElementById:id=>nodes.get(id)||null,querySelector:()=>null},console,setTimeout,clearTimeout};
vm.createContext(sandbox);
vm.runInContext(fs.readFileSync('web/assets/runtime.release.js','utf8').replace(/start\(\);\s*$/,''),sandbox);
const run=code=>vm.runInContext(code,sandbox);
run(`state.files.set('rain',{id:'rain',status:'ready',displayName:'rain.csv',parsed:{format:'tabular_csv',columns:['Value'],metadata:{}}});state.files.set('obs',{id:'obs',status:'ready',displayName:'obs.csv',parsed:{format:'tabular_csv',columns:['Level (m)'],metadata:{}}});`);
const rain=run(`sourceKey('rain','Value')`),obs=run(`sourceKey('obs','Level (m)')`);
nodes.get('rainSelect').value=rain;
assert.equal(run('genericSeriesSemanticsRows().length'),1);
assert.equal(run('genericSeriesSemanticsRows()[0].quantity'),'rainfall');
run('renderSeriesSemanticsOverrides()');
assert.equal(nodes.get('seriesSemanticsPanel').hidden,false);
assert(nodes.get('seriesSemanticsRows').innerHTML.includes('value="mm/h"'));
assert(nodes.get('seriesSemanticsRows').innerHTML.includes('value="mm"'));
assert(nodes.get('seriesSemanticsRows').innerHTML.includes('data-rainfall-semantics-key'));
assert(nodes.get('seriesSemanticsRows').innerHTML.includes('Incremental depth per interval'));
assert(nodes.get('seriesSemanticsRows').innerHTML.includes('does not silently convert rainfall values'));
nodes.get('observedSelect').value=obs;
assert.equal(run('genericSeriesSemanticsRows().map(x=>x.role).join("|")'),'Observed|Rainfall');
nodes.get('modelSelect').selectedOptions=[{value:rain}];
assert.equal(run('genericSeriesSemanticsRows().length'),2);
assert.equal(run('genericSeriesSemanticsRows()[1].role'),'Model 1 + Rainfall');
nodes.get('rainSelect').value='';nodes.get('modelSelect').selectedOptions=[];
assert.equal(run('genericSeriesSemanticsRows().length'),1);
console.log('Rainfall semantic UI regressions passed: selected-only rainfall row, explicit intensity/depth meaning, assignment-only units, stable ordering and deduplication.');
