const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={pyodide:null,engine:null,files:new Map(),seq:0,analysis:null,exclusions:[],workspacePending:null};
const PY_MODULES=['icm_workbench/__init__.py','icm_workbench/domain/__init__.py','icm_workbench/domain/models.py','icm_workbench/parsers/__init__.py','icm_workbench/parsers/common.py','icm_workbench/parsers/csv.py','icm_workbench/parsers/fdv.py','icm_workbench/parsers/rainfall.py','icm_workbench/analysis/__init__.py','icm_workbench/analysis/alignment.py','icm_workbench/analysis/metrics.py','icm_workbench/analysis/exclusions.py','icm_workbench/analysis/spills.py'];

function busy(on,text='Working…'){ $('#busyText').textContent=text; $('#busyOverlay').classList.toggle('hidden',!on); }
function msg(text,type='info'){const d=document.createElement('div');d.className=`message ${type}`;d.textContent=text;return d}
function formatBytes(n){if(n<1024)return `${n} B`;if(n<1048576)return `${(n/1024).toFixed(1)} KB`;return `${(n/1048576).toFixed(1)} MB`}
function fmt(v,d=3){return v==null||Number.isNaN(Number(v))?'—':Number(v).toLocaleString(undefined,{maximumFractionDigits:d})}
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function download(name,text,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}

async function initEngine(){try{busy(true,'Starting browser calculation engine…');const py=await loadPyodide({indexURL:'https://cdn.jsdelivr.net/pyodide/v0.27.7/full/'});await py.loadPackage(['numpy','pandas']);py.FS.mkdirTree('/app/icm_workbench');for(const mod of PY_MODULES){const res=await fetch(`python/${mod}`,{cache:'no-cache'});if(!res.ok)throw new Error(`Missing calculation module: ${mod}`);const path=`/app/${mod}`;py.FS.mkdirTree(path.slice(0,path.lastIndexOf('/')));py.FS.writeFile(path,await res.text())}const bridge=await (await fetch('engine_bridge.py',{cache:'no-cache'})).text();py.FS.writeFile('/app/engine_bridge.py',bridge);py.runPython("import sys; sys.path.insert(0,'/app'); import engine_bridge");state.pyodide=py;state.engine=py.pyimport('engine_bridge');$('#engineBadge').textContent='Calculation engine ready';$('#engineBadge').className='status-badge ready';await parsePending();}catch(e){console.error(e);$('#engineBadge').textContent='Engine failed';$('#engineBadge').className='status-badge error';$('#dataWarnings').replaceChildren(msg(`Browser engine could not start: ${e.message}`,'error'));}finally{busy(false)}}

async function fileText(file){return await file.text()}
async function addFiles(files){const arr=[...files].filter(f=>/\.(csv|fdv|r|txt)$/i.test(f.name));for(const f of arr){const key=`f${++state.seq}`;state.files.set(key,{key,file:f,name:f.name,size:f.size,modified:f.lastModified,role:'unassigned',column:null,status:state.engine?'parsing':'queued',parsed:null,error:null})}renderPool();if(state.engine)await parsePending()}
async function parsePending(){const todo=[...state.files.values()].filter(x=>['queued','parsing'].includes(x.status)&&!x.parsed);for(const item of todo){item.status='parsing';renderPool();try{const raw=state.engine.put_file(item.key,item.name,await fileText(item.file));item.parsed=JSON.parse(raw);item.status='ready';item.column=item.parsed.columns[0]||null}catch(e){item.status='error';item.error=String(e.message||e)}renderPool()}applyPendingWorkspace();}
function renderPool(){const q=$('#poolSearch').value.toLowerCase();const body=$('#poolBody');body.innerHTML='';let ready=0;for(const item of state.files.values()){if(q&&!item.name.toLowerCase().includes(q))continue;if(item.status==='ready')ready++;const tr=document.createElement('tr');const cols=item.parsed?.columns||[];tr.innerHTML=`<td><div class="file-name" title="${escapeHtml(item.name)}">${escapeHtml(item.name)}</div><div class="file-meta">${item.parsed?.rows?item.parsed.rows.toLocaleString()+' rows':''}</div></td><td><span class="format-pill">${escapeHtml((item.parsed?.format||item.name.split('.').pop()||'file').toUpperCase())}</span></td><td>${formatBytes(item.size)}</td><td class="${item.status==='ready'?'parse-ok':item.status==='error'?'parse-error':''}">${item.status==='ready'?'Ready':item.status==='error'?'Error':item.status==='queued'?'Queued':'Parsing…'}${item.error?`<div class="file-meta" title="${escapeHtml(item.error)}">${escapeHtml(item.error.slice(0,90))}</div>`:''}</td><td><select class="input role" data-key="${item.key}" ${item.status!=='ready'?'disabled':''}><option value="unassigned">Unassigned</option><option value="observed">Observed</option><option value="simulated">Simulated</option><option value="rainfall">Rainfall</option><option value="overflow">Overflow flow</option></select></td><td><select class="input series" data-key="${item.key}" ${item.status!=='ready'?'disabled':''}>${cols.map(c=>`<option value="${escapeHtml(c)}">${escapeHtml(c)}</option>`).join('')}</select></td><td><button class="button ghost remove" data-key="${item.key}">Remove</button></td>`;body.appendChild(tr);tr.querySelector('.role').value=item.role;tr.querySelector('.series').value=item.column||''}
$('#poolSummary').textContent=state.files.size?`${state.files.size} file(s) in pool · ${[...state.files.values()].filter(x=>x.status==='ready').length} parsed successfully`:'No files loaded.';const obs=[...state.files.values()].some(x=>x.role==='observed'&&x.status==='ready');const sims=[...state.files.values()].some(x=>x.role==='simulated'&&x.status==='ready');$('#runAnalysis').disabled=!(obs&&sims&&state.engine)}
function enforceSingle(role,key){if(!['observed','rainfall','overflow'].includes(role))return;for(const x of state.files.values())if(x.key!==key&&x.role===role)x.role='unassigned'}

function config(){const obs=[...state.files.values()].find(x=>x.role==='observed');const sims=[...state.files.values()].filter(x=>x.role==='simulated');const rain=[...state.files.values()].find(x=>x.role==='rainfall');return{observed_id:obs?.key,observed_col:obs?.column,simulated:sims.map(x=>({id:x.key,col:x.column})),rainfall_id:rain?.key,rainfall_col:rain?.column,start:$('#analysisStart').value||null,end:$('#analysisEnd').value||null,max_gap_seconds:Number($('#maxGapMin').value||15)*60,observed_threshold:$('#obsThreshold').value===''?null:Number($('#obsThreshold').value),model_threshold:$('#modelThreshold').value===''?null:Number($('#modelThreshold').value),exclusions:state.exclusions.filter(e=>e.start&&e.end&&e.reason)}}
async function runAnalysis(goCompare=true){if(!state.engine)return;try{busy(true,'Running audited analysis…');state.analysis=JSON.parse(state.engine.analyse(JSON.stringify(config())));renderAnalysis();if(goCompare)showView('compare')}catch(e){console.error(e);$('#dataWarnings').replaceChildren(msg(`Analysis failed: ${e.message}`,'error'));showView('data')}finally{busy(false)}}
function renderAnalysis(){const a=state.analysis;if(!a)return;const comps=a.comparisons||[];const cards=[];if(comps[0]){const m=comps[0].metrics||{};cards.push(['Paired points',m.pairs],['RMSE',fmt(m.rmse)],['Mean bias',fmt(m.mean_bias)],['NSE',fmt(m.nse)],['KGE 2009',fmt(m.kge_2009)])}$('#metricCards').innerHTML=cards.map(([k,v])=>`<div class="metric"><span>${escapeHtml(k)}</span><strong>${escapeHtml(v)}</strong></div>`).join('');
const traces=[{x:a.observed.x,y:a.observed.y,name:`Observed: ${a.observed.name}`,mode:'lines',line:{width:2.2,color:'#d63131'}}];for(const s of a.simulated||[])traces.push({x:s.x,y:s.y,name:`Simulated: ${s.name}`,mode:'lines',line:{width:1.8}});if(a.rainfall)traces.push({x:a.rainfall.x,y:a.rainfall.y,name:`Rainfall: ${a.rainfall.name}`,type:'bar',yaxis:'y2',opacity:.28});Plotly.react('mainChart',traces,{margin:{l:55,r:55,t:25,b:55},hovermode:'x unified',legend:{orientation:'h'},xaxis:{title:'Time'},yaxis:{title:'Observed / modelled'},yaxis2:{title:'Rainfall',overlaying:'y',side:'right',autorange:'reversed',showgrid:false}},{responsive:true,displaylogo:false});
if(comps[0]){const p=comps[0].paired||[];Plotly.react('residualChart',[{x:p.map(r=>r.timestamp),y:p.map(r=>r.sim-r.obs),mode:'lines',name:'Model − observed'}],{margin:{l:50,r:15,t:15,b:45},xaxis:{title:'Time'},yaxis:{title:'Residual'}},{responsive:true,displaylogo:false});const o=p.map(r=>r.obs).filter(Number.isFinite).sort((x,y)=>y-x),s=p.map(r=>r.sim).filter(Number.isFinite).sort((x,y)=>y-x),xo=o.map((_,i)=>100*i/Math.max(o.length-1,1)),xs=s.map((_,i)=>100*i/Math.max(s.length-1,1));Plotly.react('fdcChart',[{x:xo,y:o,name:'Observed',mode:'lines'},{x:xs,y:s,name:comps[0].name,mode:'lines'}],{margin:{l:50,r:15,t:15,b:45},xaxis:{title:'Exceedance (%)'},yaxis:{title:'Value'}},{responsive:true,displaylogo:false})}
$('#comparisonTable').innerHTML=`<h3>Scenario comparison</h3>${table(comps.map(c=>({Scenario:c.name,Pairs:c.metrics?.pairs??0,RMSE:fmt(c.metrics?.rmse),Bias:fmt(c.metrics?.mean_bias),NSE:fmt(c.metrics?.nse),KGE:fmt(c.metrics?.kge_2009),'Peak lag min':fmt(c.metrics?.peak_timing_minutes_model_minus_observed,1)})))}`;renderSpills();renderEvents()}
function table(rows){if(!rows?.length)return '<p class="muted">No results available.</p>';const keys=Object.keys(rows[0]);return `<div class="table-wrap"><table class="data-table"><thead><tr>${keys.map(k=>`<th>${escapeHtml(k)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${keys.map(k=>`<td>${escapeHtml(r[k]??'')}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function renderSpills(){const s=state.analysis?.spills;if(!s){$('#spillSummary').innerHTML='';$('#obsSpillTable').innerHTML='<p class="muted">Set an observed threshold and recalculate.</p>';$('#obsDurationTable').innerHTML='';$('#spillCompareTable').innerHTML='';return}$('#spillSummary').innerHTML=[['12/24 spill count',s.total_spill_count],['Physical duration (hr)',fmt(s.total_spill_duration_hours)],['Coverage',fmt((s.coverage_fraction||0)*100,1)+'%'],['Excluded (hr)',fmt((s.excluded_seconds||0)/3600)],['Unknown (hr)',fmt((s.unknown_seconds||0)/3600)]].map(([k,v])=>`<div class="metric"><span>${k}</span><strong>${v}</strong></div>`).join('');$('#obsSpillTable').innerHTML=table((s.monthly_counts||[]).map(r=>({Year:r.year,Month:r.month,'Spill count':r.spill_count})));$('#obsDurationTable').innerHTML=table((s.monthly_durations||[]).map(r=>({Year:r.year,Month:r.month,'Duration hr':fmt(r.duration_hours)})));const models=state.analysis.model_spills||[];const rows=models.map(m=>({Scenario:m.name,'Spill count':m.assessment.total_spill_count,'Duration hr':fmt(m.assessment.total_spill_duration_hours),Status:m.assessment.count_status,Coverage:fmt((m.assessment.coverage_fraction||0)*100,1)+'%'}));$('#spillCompareTable').innerHTML=table(rows);$('#spillMessages').replaceChildren(s.status==='partial'?msg('Observed spill assessment contains unexcluded unknown time. Counts are therefore partial rather than definitive.','warn'):msg('Observed spill assessment has complete assessable-time coverage.','info'))}
function renderEvents(){const events=state.analysis?.spills?.events||[];$('#eventTable').innerHTML=table(events.map((e,i)=>({Event:i+1,Start:e.start,End:e.end,'Duration hr':fmt(e.duration_seconds/3600)})))}

function addExclusion(data={}){state.exclusions.push({id:crypto.randomUUID?.()||String(Date.now()+Math.random()),start:data.start||'',end:data.end||'',reason:data.reason||''});renderExclusions()}
function renderExclusions(){const root=$('#exclusionList');root.innerHTML=state.exclusions.length?'':'<p class="muted">No exclusions. All available data remains assessable.</p>';for(const e of state.exclusions){const d=document.createElement('div');d.className='exclusion-row';d.innerHTML=`<label>Start<input class="input exc-start" type="datetime-local" value="${escapeHtml(e.start)}"></label><label>End<input class="input exc-end" type="datetime-local" value="${escapeHtml(e.end)}"></label><label>Reason<input class="input exc-reason" type="text" placeholder="e.g. EDM logger fault" value="${escapeHtml(e.reason)}"></label><button class="button ghost exc-remove">Remove</button>`;d.querySelector('.exc-start').onchange=x=>e.start=x.target.value;d.querySelector('.exc-end').onchange=x=>e.end=x.target.value;d.querySelector('.exc-reason').oninput=x=>e.reason=x.target.value;d.querySelector('.exc-remove').onclick=()=>{state.exclusions=state.exclusions.filter(x=>x.id!==e.id);renderExclusions()};root.appendChild(d)}}
function showView(name){$$('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${name}`));$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===name));if(state.analysis&&name==='compare')setTimeout(()=>{Plotly.Plots.resize('mainChart');Plotly.Plots.resize('residualChart');Plotly.Plots.resize('fdcChart')},30)}

function workspaceObject(){const cfg=config();return{schema_version:1,name:'ICM Browser Workspace',files:[...state.files.values()].map(x=>({name:x.name,size:x.size,role:x.role,column:x.column,format:x.parsed?.format||null})),analysis:{start:cfg.start,end:cfg.end,max_gap_seconds:cfg.max_gap_seconds,observed_threshold:cfg.observed_threshold,model_threshold:cfg.model_threshold},exclusions:state.exclusions.map(({start,end,reason})=>({start,end,reason})),saved:new Date().toISOString()}}
function applyPendingWorkspace(){const w=state.workspacePending;if(!w)return;for(const spec of w.files||[]){const candidates=[...state.files.values()].filter(x=>x.name===spec.name&&(!spec.size||x.size===spec.size));if(candidates.length===1){candidates[0].role=spec.role||'unassigned';if(candidates[0].parsed?.columns?.includes(spec.column))candidates[0].column=spec.column}}state.exclusions=(w.exclusions||[]).map(e=>({id:crypto.randomUUID?.()||String(Math.random()),...e}));$('#analysisStart').value=w.analysis?.start||'';$('#analysisEnd').value=w.analysis?.end||'';$('#maxGapMin').value=(Number(w.analysis?.max_gap_seconds||900)/60);$('#obsThreshold').value=w.analysis?.observed_threshold??'';$('#modelThreshold').value=w.analysis?.model_threshold??'';renderExclusions();renderPool();state.workspacePending=null;$('#workspaceMessage').replaceChildren(msg('Workspace configuration restored against matching filenames. Review role/channel mappings before analysis.','info'))}

function reportHtml(){const a=state.analysis,cfg=config(),ws=workspaceObject(),comps=a?.comparisons||[],s=a?.spills;const metricRows=comps.map(c=>({Scenario:c.name,Pairs:c.metrics?.pairs??0,RMSE:fmt(c.metrics?.rmse),Bias:fmt(c.metrics?.mean_bias),NSE:fmt(c.metrics?.nse),KGE:fmt(c.metrics?.kge_2009)}));return `<!doctype html><html><head><meta charset="utf-8"><title>ICM Workbench Assessment</title><style>body{font-family:Segoe UI,Arial;margin:32px;color:#17263a}table{border-collapse:collapse;width:100%;margin:10px 0 24px}th,td{border:1px solid #d8e1ea;padding:7px;text-align:left}th{background:#f2f6fa}pre{white-space:pre-wrap;background:#f6f8fa;padding:12px}</style></head><body><h1>ICM Graphing & Calibration Workbench — Assessment</h1><p>Generated ${new Date().toLocaleString()}. Browser edition; calculations executed locally using the repository Python core.</p><h2>Scenario metrics</h2>${table(metricRows)}<h2>Observed spill summary</h2>${s?table([{Count:s.total_spill_count,'Duration hr':fmt(s.total_spill_duration_hours),Coverage:fmt((s.coverage_fraction||0)*100,1)+'%',Status:s.count_status}]):'<p>Not calculated.</p>'}<h2>Exclusion audit</h2>${table(state.exclusions.map(e=>({Start:e.start,End:e.end,Reason:e.reason})))}<h2>Configuration provenance</h2><pre>${escapeHtml(JSON.stringify(ws,null,2))}</pre></body></html>`}

async function collectDroppedItems(dt){const files=[];const walk=entry=>new Promise(resolve=>{if(entry.isFile)entry.file(f=>{files.push(f);resolve()},resolve);else if(entry.isDirectory){const reader=entry.createReader(),read=()=>reader.readEntries(async entries=>{if(!entries.length)return resolve();for(const e of entries)await walk(e);read()},resolve);read()}else resolve()});const items=[...dt.items];for(const item of items){const entry=item.webkitGetAsEntry?.();if(entry)await walk(entry);else if(item.kind==='file'){const f=item.getAsFile();if(f)files.push(f)}}return files.length?files:[...dt.files]}

$$('.nav').forEach(b=>b.onclick=()=>showView(b.dataset.view));$('#folderInput').onchange=e=>addFiles(e.target.files);$('#fileInput').onchange=e=>addFiles(e.target.files);$('#poolSearch').oninput=renderPool;$('#clearPool').onclick=()=>{for(const x of state.files.values())try{state.engine?.drop_file(x.key)}catch{}state.files.clear();state.analysis=null;renderPool()};$('#poolBody').onchange=e=>{const key=e.target.dataset.key,item=state.files.get(key);if(!item)return;if(e.target.classList.contains('role')){item.role=e.target.value;enforceSingle(item.role,key);renderPool()}if(e.target.classList.contains('series'))item.column=e.target.value};$('#poolBody').onclick=e=>{if(e.target.classList.contains('remove')){const key=e.target.dataset.key;try{state.engine?.drop_file(key)}catch{}state.files.delete(key);renderPool()}};$('#runAnalysis').onclick=()=>runAnalysis(true);$('#runSpills').onclick=()=>runAnalysis(false);$('#addExclusion').onclick=()=>addExclusion();$('#exportWorkspace').onclick=()=>download('icm-workbench.workspace.json',JSON.stringify(workspaceObject(),null,2));$('#workspaceInput').onchange=async e=>{try{state.workspacePending=JSON.parse(await e.target.files[0].text());applyPendingWorkspace()}catch(err){$('#workspaceMessage').replaceChildren(msg(`Workspace import failed: ${err.message}`,'error'))}};$('#downloadReport').onclick=()=>{if(!state.analysis)return alert('Run analysis first.');download('icm-assessment.html',reportHtml(),'text/html')};$('#downloadWorkspaceReport').onclick=()=>{if(!state.analysis)return alert('Run analysis first.');download('icm-analysis-summary.json',JSON.stringify({workspace:workspaceObject(),analysis:state.analysis},null,2))};
const dz=$('#dropZone');['dragenter','dragover'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',async e=>addFiles(await collectDroppedItems(e.dataTransfer)));dz.onclick=()=>$('#fileInput').click();
renderPool();renderExclusions();initEngine();